services:

  backend:
    build: ./backend
    networks:
      - my_network
    environment:  
      - PORT=3001

  frontend:
    build: ./frontend
    networks:
      - my_network
    environment:  
      - BACKEND_URL=http://backend:3001

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my_network
    environment:  
      - BACKEND_PORT=3001
    

networks:
  my_network: