services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: cyburn-backend
    container_name: cyburn-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - cyburn-network
    depends_on:
      - db
      - lab01
      - lab02
  db:
    image: mongo
    hostname: mongo
    container_name: cyburn-db
    # ports:
    # - "270/17:27017"
    networks:
      - cyburn-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: cyburn-frontend
    container_name: cyburn-frontend
    ports:
      - "3000:3000"
    networks:
      - cyburn-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_URL=http://localhost

  lab01:
    build:
      context: labs/lab01
      dockerfile: Dockerfile
    image: cyburn-lab01
    container_name: cyburn-lab01
    ports:
      - "8081:80"
    volumes:
      - ./labs/lab01/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cyburn-network

  lab02:
    build:
      context: labs/lab02
      dockerfile: Dockerfile
    image: cyburn-lab02
    container_name: cyburn-lab02
    ports:
      - "8082:80"
    volumes:
      - ./labs/lab02/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cyburn-network

networks:
  cyburn-network:
    driver: bridge
    
