services:
  backend:
    build: ./backend
    networks:
      - my_network

  frontend:
    build: ./frontend
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network: